spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(LET/TvulAeK1cyMgW2B0ZXkrT4XcYCgTDdvFsQCL5yNlIbgCLg2oS0f+dzQqoCP0OA2GQDjlyb0uKO8S79DFyPQraCeq7ET1nmSSDj5DsMLvAtQ8F02r6Q==)
    username: ENC(IcZGTKix8EdkHPilDy82CQ==)
    password: ENC(sSAEDfEoJabK/NnjUT9ULp4LxgcxlsyN)

application:
  security:
    jwt:
      secretKey: BQFXy4afcXCxKI7BNo8argHNwP5nh6AiCcSyLnkCs0xZkS8RPImDlK42uE4Mz/DmFEidO0ALl7Lkxs2s9aGwmw==
      expiration_time: 600000 # 10분
      refresh-token:
        expiration_time: 86400000 #1
  redis:
    host: redis
    port: 6379

cloud:
  aws:
    credentials:
      secret-key: ENC(72uIBqAtUh5oQRTdWPpyzkrNa8LJ8cjOHDz/1WZezdeChWKRG4ybe8seo7nArw7lS9CzKAfFe6k=)
      access-key: ENC(SxEadoBpc86A6fjuzhpmvNSbKNlgksM+mrzmL9kCDqc=)
    region:
      static: ENC(6EUUAT6aKM4cwjK1i88BRhFrvovaJWOh)
    s3:
      bucketName: ENC(AxkWVAblj5LXXbz3TDkaGJABO7vNbY98)
    stack:
      auto: false

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}